docs : add documentation for hook functions #67
react-auth-kit/react-auth-kit pull request #68
Opened 2020-10-06 14:22 UTC by Hardik0307

- [x] I have read the **CONTRIBUTING** document.
- [x] added document for all hook file functions.
- [x] followed [JsDoc](https://jsdoc.app/)

Kindly Review.

Fixes #67

2020-10-06 14:43 UTC, Hardik0307 commented
@darkmatter18  check test considering `no-trailing-spaces` for comments too.

to avoid we have to do,
in the, **package.json**
> npm test:lint :  eslint ...  --fix

2020-10-06 15:55 UTC, darkmatter18 requested changes
Nice Work. But just a minor change and we are good to go.

2020-10-06 15:55 UTC, darkmatter18 commented on package.json
> +    "test:lint": "eslint src/**/*.ts src/**/*.tsx --fix",
Fix Command is there, please undo it

2020-10-06 17:22 UTC, Hardik0307 commented on package.json
> +    "test:lint": "eslint src/**/*.ts src/**/*.tsx --fix",
Resolved @darkmatter18 .
Have a look.

2020-10-07 02:38 UTC, darkmatter18 commented
LGTM. Thanks for your contribution. @Hardik0307 🥇

2020-10-07 02:38 UTC, merged